version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:15.4
    restart: always
    ports:
      - 5432:5432
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_DB=app
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  mysql:
    container_name: mysql
    image: mysql:8.1.0
    restart: always
    ports:
      - 3306:3306
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=app
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
